import os


def borrar_fotos(nombres_a_borrar):
    # Obtén la ruta del directorio actual donde se encuentra este script
    carpeta_actual = os.path.dirname(os.path.abspath(__file__))

    # Obtén la lista de archivos en la carpeta
    archivos_en_carpeta = os.listdir(carpeta_actual)

    for nombre_archivo in archivos_en_carpeta:
        # Verifica si el nombre del archivo coincide con alguno de los nombres a borrar
        if nombre_archivo in nombres_a_borrar:
            # Crea la ruta completa al archivo
            ruta_completa = os.path.join(carpeta_actual, nombre_archivo)

            try:
                # Intenta eliminar el archivo
                os.remove(ruta_completa)
                print(f"Archivo eliminado: {ruta_completa}")
            except Exception as e:
                print(
                    f"No se pudo eliminar el archivo {ruta_completa}. Error: {e}")


nombres_pokemon = [
    "BULBASAUR.png", "IVYSAUR.png", "VENUSAUR.png", "CHARMANDER.png", "CHARMELEON.png",
    "CHARIZARD.png", "SQUIRTLE.png", "WARTORTLE.png", "BLASTOISE.png", "CATERPIE.png",
    "METAPOD.png", "BUTTERFREE.png", "WEEDLE.png", "KAKUNA.png", "BEEDRILL.png",
    "PIDGEY.png", "PIDGEOTTO.png", "PIDGEOT.png", "RATTATA.png", "RATICATE.png",
    "SPEAROW.png", "FEAROW.png", "EKANS.png", "ARBOK.png", "PIKACHU.png",
    "RAICHU.png", "SANDSHREW.png", "SANDSLASH.png", "NIDORAN-F.png", "NIDORINA.png",
    "NIDOQUEEN.png", "NIDORAN-M.png", "NIDORINO.png", "NIDOKING.png", "CLEFAIRY.png",
    "CLEFABLE.png", "VULPIX.png", "NINETALES.png", "JIGGLYPUFF.png", "WIGGLYTUFF.png",
    "ZUBAT.png", "GOLBAT.png", "ODDISH.png", "GLOOM.png", "VILEPLUME.png",
    "PARAS.png", "PARASECT.png", "VENONAT.png", "VENOMOTH.png", "DIGLETT.png",
    "DUGTRIO.png", "MEOWTH.png", "PERSIAN.png", "PSYDUCK.png", "GOLDUCK.png",
    "MANKEY.png", "PRIMEAPE.png", "GROWLITHE.png", "ARCANINE.png", "POLIWAG.png",
    "POLIWHIRL.png", "POLIWRATH.png", "ABRA.png", "KADABRA.png", "ALAKAZAM.png",
    "MACHOP.png", "MACHOKE.png", "MACHAMP.png", "BELLSPROUT.png", "WEEPINBELL.png",
    "VICTREEBEL.png", "TENTACOOL.png", "TENTACRUEL.png", "GEODUDE.png", "GRAVELER.png",
    "GOLEM.png", "PONYTA.png", "RAPIDASH.png", "SLOWPOKE.png", "SLOWBRO.png",
    "MAGNEMITE.png", "MAGNETON.png", "FARFETCHD.png", "DODUO.png", "DODRIO.png",
    "SEEL.png", "DEWGONG.png", "GRIMER.png", "MUK.png", "SHELLDER.png",
    "CLOYSTER.png", "GASTLY.png", "HAUNTER.png", "GENGAR.png", "ONIX.png",
    "DROWZEE.png", "HYPNO.png", "KRABBY.png", "KINGLER.png", "VOLTORB.png",
    "ELECTRODE.png", "EXEGGCUTE.png", "EXEGGUTOR.png", "CUBONE.png", "MAROWAK.png",
    "HITMONLEE.png", "HITMONCHAN.png", "LICKITUNG.png", "KOFFING.png", "WEEZING.png",
    "RHYHORN.png", "RHYDON.png", "CHANSEY.png", "TANGELA.png", "KANGASKHAN.png",
    "HORSEA.png", "SEADRA.png", "GOLDEEN.png", "SEAKING.png", "STARYU.png",
    "STARMIE.png", "MR-MIME.png", "SCYTHER.png", "JYNX.png", "ELECTABUZZ.png",
    "MAGMAR.png", "PINSIR.png", "TAUROS.png", "MAGIKARP.png", "GYARADOS.png",
    "LAPRAS.png", "DITTO.png", "EEVEE.png", "VAPOREON.png", "JOLTEON.png",
    "FLAREON.png", "PORYGON.png", "OMANYTE.png", "OMASTAR.png", "KABUTO.png",
    "KABUTOPS.png", "AERODACTYL.png", "SNORLAX.png", "ARTICUNO.png", "ZAPDOS.png",
    "MOLTRES.png", "DRATINI.png", "DRAGONAIR.png", "DRAGONITE.png", "MEWTWO.png",
    "MEW.png", "CHIKORITA.png", "BAYLEEF.png", "MEGANIUM.png", "CYNDAQUIL.png",
    "QUILAVA.png", "TYPHLOSION.png", "TOTODILE.png", "CROCONAW.png", "FERALIGATR.png",
    "SENTRET.png", "FURRET.png", "HOOTHOOT.png", "NOCTOWL.png", "LEDYBA.png",
    "LEDIAN.png", "SPINARAK.png", "ARIADOS.png", "CROBAT.png", "CHINCHOU.png",
    "LANTURN.png", "PICHU.png", "CLEFFA.png", "IGGLYBUFF.png", "TOGEPI.png",
    "TOGETIC.png", "NATU.png", "XATU.png", "MAREEP.png", "FLAAFFY.png",
    "AMPHAROS.png", "BELLOSSOM.png", "MARILL.png", "AZUMARILL.png", "SUDOWOODO.png",
    "POLITOED.png", "HOPPIP.png", "SKIPLOOM.png", "JUMPLUFF.png", "AIPOM.png",
    "SUNKERN.png", "SUNFLORA.png", "YANMA.png", "WOOPER.png", "QUAGSIRE.png",
    "ESPEON.png", "UMBREON.png", "MURKROW.png", "SLOWKING.png", "MISDREAVUS.png",
    "UNOWN.png", "WOBBUFFET.png", "GIRAFARIG.png", "PINECO.png", "FORRETRESS.png",
    "DUNSPARCE.png", "GLIGAR.png", "STEELIX.png", "SNUBBULL.png", "GRANBULL.png",
    "QWILFISH.png", "SCIZOR.png", "SHUCKLE.png", "HERACROSS.png", "SNEASEL.png",
    "TEDDIURSA.png", "URSARING.png", "SLUGMA.png", "MAGCARGO.png", "SWINUB.png",
    "PILOSWINE.png", "CORSOLA.png", "REMORAID.png", "OCTILLERY.png", "DELIBIRD.png",
    "MANTINE.png", "SKARMORY.png", "HOUNDOUR.png", "HOUNDOOM.png", "KINGDRA.png",
    "PHANPY.png", "DONPHAN.png", "PORYGON2.png", "STANTLER.png", "SMEARGLE.png",
    "TYROGUE.png", "HITMONTOP.png", "SMOOCHUM.png", "ELEKID.png", "MAGBY.png",
    "MILTANK.png", "BLISSEY.png", "RAIKOU.png", "ENTEI.png", "SUICUNE.png",
    "LARVITAR.png", "PUPITAR.png", "TYRANITAR.png", "LUGIA.png", "HO-OH.png",
    "CELEBI.png", "TREECKO.png", "GROVYLE.png", "SCEPTILE.png", "TORCHIC.png",
    "COMBUSKEN.png", "BLAZIKEN.png", "MUDKIP.png", "MARSHTOMP.png", "SWAMPERT.png",
    "POOCHYENA.png", "MIGHTYENA.png", "ZIGZAGOON.png", "LINOONE.png", "WURMPLE.png",
    "SILCOON.png", "BEAUTIFLY.png", "CASCOON.png", "DUSTOX.png", "LOTAD.png",
    "LOMBRE.png", "LUDICOLO.png", "SEEDOT.png", "NUZLEAF.png", "SHIFTRY.png",
    "TAILOW.png", "SWELLOW.png", "WINGULL.png", "PELIPPER.png", "RALTS.png",
    "KIRLIA.png", "GARDEVOIR.png", "SURSKIT.png", "MASQUERAIN.png", "SHROOMISH.png",
    "BRELOOM.png", "SLAKOTH.png", "VIGOROTH.png", "SLAKING.png", "NINCADA.png",
    "NINJASK.png", "SHEDINJA.png", "WHISMUR.png", "LOUDRED.png", "EXPLOUD.png",
    "MAKUHITA.png", "HARIYAMA.png", "AZURILL.png", "NOSEPASS.png", "SKITTY.png",
    "DELCATTY.png", "SABLEYE.png", "MAWILE.png", "ARON.png", "LAIRON.png",
    "AGGRON.png", "MEDITITE.png", "MEDICHAM.png", "ELECTRIKE.png", "MANECTRIC.png",
    "PLUSLE.png", "MINUN.png", "VOLBEAT.png", "ILLUMISE.png", "ROSELIA.png",
    "GULPIN.png", "SWALOT.png", "CARVANHA.png", "SHARPEDO.png", "WAILMER.png",
    "WAILORD.png", "NUMEL.png", "CAMERUPT.png", "TORKOAL.png", "SPOINK.png",
    "GRUMPIG.png", "SPINDA.png", "TRAPINCH.png", "VIBRAVA.png", "FLYGON.png",
    "CACNEA.png", "CACTURNE.png", "SWABLU.png", "ALTARIA.png", "ZANGOOSE.png",
    "SEVIPER.png", "LUNATONE.png", "SOLROCK.png", "BARBOACH.png", "WHISCASH.png",
    "CORPHISH.png", "CRAWDAUNT.png", "BALTOY.png", "CLAYDOL.png", "LILEEP.png",
    "CRADILY.png", "ANORITH.png", "ARMALDO.png", "FEEBAS.png", "MILOTIC.png",
    "CASTFORM.png", "KECLEON.png", "SHUPPET.png", "BANETTE.png", "DUSKULL.png",
    "DUSCLOPS.png", "TROPIUS.png", "CHIMECHO.png", "ABSOL.png", "WYNAUT.png",
    "SNORUNT.png", "GLALIE.png", "SPHEAL.png", "SEALEO.png", "WALREIN.png",
    "CLAMPERL.png", "HUNTAIL.png", "GOREBYSS.png", "RELICANTH.png", "LUVDISC.png",
    "BAGON.png", "SHELGON.png", "SALAMENCE.png", "BELDUM.png", "METANG.png",
    "METAGROSS.png", "REGIROCK.png", "REGICE.png", "REGISTEEL.png", "LATIAS.png",
    "LATIOS.png", "KYOGRE.png", "GROUDON.png", "RAYQUAZA.png", "JIRACHI.png",
    "DEOXYS.png", "TURTWIG.png", "GROTLE.png", "TORTERRA.png", "CHIMCHAR.png",
    "MONFERNO.png", "INFERNAPE.png", "PIPLUP.png", "PRINPLUP.png", "EMPOLEON.png",
    "STARLY.png", "STARAVIA.png", "STARAPTOR.png", "BIDOOF.png", "BIBAREL.png",
    "KRICKETOT.png", "KRICKETUNE.png", "SHINX.png", "LUXIO.png", "LUXRAY.png",
    "BUDEW.png", "ROSERADE.png", "CRANIDOS.png", "RAMPARDOS.png", "SHIELDON.png",
    "BASTIODON.png", "BURMY.png", "WORMADAM.png", "MOTHIM.png", "COMBEE.png",
    "VESPIQUEN.png", "PACHIRISU.png", "BUIZEL.png", "FLOATZEL.png", "CHERUBI.png",
    "CHERRIM.png", "SHELLOS.png", "GASTRODON.png", "AMBIPOM.png", "DRIFLOON.png",
    "DRIFBLIM.png", "BUNEARY.png", "LOPUNNY.png", "MISMAGIUS.png", "HONCHKROW.png",
    "GLAMEOW.png", "PURUGLY.png", "CHINGLING.png", "STUNKY.png", "SKUNTANK.png",
    "BRONZOR.png", "BRONZONG.png", "BONSLY.png", "MIME-JR.png", "HAPPINY.png",
    "CHATOT.png", "SPIRITOMB.png", "GIBLE.png", "GABITE.png", "GARCHOMP.png",
    "MUNCHLAX.png", "RIOLU.png", "LUCARIO.png", "HIPPOPOTAS.png", "HIPPOWDON.png",
    "SKORUPI.png", "DRAPION.png", "CROAGUNK.png", "TOXICROAK.png", "CARNIVINE.png",
    "FINNEON.png", "LUMINEON.png", "MANTYKE.png", "SNOVER.png", "ABOMASNOW.png",
    "WEAVILE.png", "MAGNEZONE.png", "LICKILICKY.png", "RHYPERIOR.png", "TANGROWTH.png",
    "ELECTIVIRE.png", "MAGMORTAR.png", "TOGEKISS.png", "YANMEGA.png", "LEAFEON.png",
    "GLACEON.png", "GLISCOR.png", "MAMOSWINE.png", "PORYGON-Z.png", "GALLADE.png",
    "PROBOPASS.png", "DUSKNOIR.png", "FROSLASS.png", "ROTOM.png", "UXIE.png",
    "MESPRIT.png", "AZELF.png", "DIALGA.png", "PALKIA.png", "HEATRAN.png",
    "REGIGIGAS.png", "GIRATINA.png", "CRESSELIA.png", "PHIONE.png", "MANAPHY.png",
    "DARKRAI.png", "SHAYMIN.png", "ARCEUS.png", "VICTINI.png", "SNIVY.png",
    "SERVINE.png", "SERPERIOR.png", "TEPIG.png", "PIGNITE.png", "EMBOAR.png",
    "OSHAWOTT.png", "DEWOTT.png", "SAMUROTT.png", "PATRAT.png", "WATCHOG.png",
    "LILLIPUP.png", "HERDIER.png", "STOUTLAND.png", "PURRLOIN.png", "LIEPARD.png",
    "PANSAGE.png", "SIMISAGE.png", "PANSEAR.png", "SIMISEAR.png", "PANPOUR.png",
    "SIMIPOUR.png", "MUNNA.png", "MUSHARNA.png", "PIDOVE.png", "TRANQUILL.png",
    "UNFEZANT.png", "BLITZLE.png", "ZEBSTRIKA.png", "ROGGENROLA.png", "BOLDORE.png",
    "GIGALITH.png", "WOOBAT.png", "SWOOBAT.png", "DRILBUR.png", "EXCADRILL.png",
    "AUDINO.png", "TIMBURR.png", "GURDURR.png", "CONKELDURR.png", "TYMPOLE.png",
    "PALPITOAD.png", "SEISMITOAD.png", "THROH.png", "SAWK.png", "SEWADDLE.png",
    "SWADLOON.png", "LEAVANNY.png", "VENIPEDE.png", "WHIRLIPEDE.png", "SCOLIPEDE.png",
    "COTTONEE.png", "WHIMSICOTT.png", "PETILIL.png", "LILLIGANT.png", "BASCULIN.png",
    "SANDILE.png", "KROKOROK.png", "KROOKODILE.png", "DARUMAKA.png", "DARMANITAN.png",
    "MARACTUS.png", "DWEBBLE.png", "CRUSTLE.png", "SCRAGGY.png", "SCRAFTY.png",
    "SIGILYPH.png", "YAMASK.png", "COFAGRIGUS.png", "TIRTOUGA.png", "CARRACOSTA.png",
    "ARCHEN.png", "ARCHEOPS.png", "TRUBBISH.png", "GARBODOR.png", "ZORUA.png",
    "ZOROARK.png", "MINCCINO.png", "CINCCINO.png", "GOTHITA.png", "GOTHORITA.png",
    "GOTHITELLE.png", "SOLOSIS.png", "DUOSION.png", "REUNICLUS.png", "DUCKLETT.png",
    "SWANNA.png", "VANILLITE.png", "VANILLISH.png", "VANILLUXE.png", "DEERLING.png",
    "SAWSBUCK.png", "EMOLGA.png", "KARRABLAST.png", "ESCAVALIER.png", "FOONGUS.png",
    "AMOONGUSS.png", "FRILLISH.png", "JELLICENT.png", "ALOMOMOLA.png", "JOLTIK.png",
    "GALVANTULA.png", "FERROSEED.png", "FERROTHORN.png", "KLINK.png", "KLANG.png",
    "KLINKLANG.png", "TYNAMO.png", "EELEKTRIK.png", "EELEKTROSS.png", "ELGYEM.png",
    "BEHEEYEM.png", "LITWICK.png", "LAMPENT.png", "CHANDELURE.png", "AXEW.png",
    "FRAXURE.png", "HAXORUS.png", "CUBCHOO.png", "BEARTIC.png", "CRYOGONAL.png",
    "SHELMET.png", "ACCELGOR.png", "STUNFISK.png", "MIENFOO.png", "MIENSHAO.png",
    "DRUDDIGON.png", "GOLETT.png", "GOLURK.png", "PAWNIARD.png", "BISHARP.png",
    "BOUFFALANT.png", "RUFFLET.png", "BRAVIARY.png", "VULLABY.png", "MANDIBUZZ.png",
    "HEATMOR.png", "DURANT.png", "DEINO.png", "ZWEILOUS.png", "HYDREIGON.png",
    "LARVESTA.png", "VOLCARONA.png", "COBALION.png", "TERRAKION.png", "VIRIZION.png",
    "TORNADUS.png", "THUNDURUS.png", "RESHIRAM.png", "ZEKROM.png", "LANDORUS.png",
    "KYUREM.png", "KELDEO.png", "MELLOETTA.png", "GENESECT.png"
]

borrar_fotos(nombres_pokemon)
